# .github/workflows/parallel_backfill.yml
name: Parallel Commit Backfill

on:
  workflow_dispatch:
    inputs:
      days:
        description: "Days back to backfill"
        default: 30
        required: false

jobs:
  backfill:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chunk: [0,1,2,3,4,5]       # 6 chunks
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java & Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven openjdk-17-jdk

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Compute date window
        id: dates
        run: |
          END=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          CHUNK_SIZE=$(( ( ${{ github.event.inputs.days }} + 5 ) / 6 ))
          OFFSET=$(( CHUNK_SIZE * matrix.chunk ))
          START=$(date -u -d "$END - $OFFSET days" +"%Y-%m-%dT%H:%M:%SZ")
          END_CHUNK=$(date -u -d "$START + $CHUNK_SIZE days" +"%Y-%m-%dT%H:%M:%SZ")
          echo "::set-output name=start::$START"
          echo "::set-output name=end::$END_CHUNK"

      - name: Run backfill for chunk ${{ matrix.chunk }}
        run: |
          CHUNK_DIR="data/chunk-${{ matrix.chunk }}"
          scripts/.pinot_backfill_commit_compare.sh \
            --start "${{ steps.dates.outputs.start }}" \
            --end   "${{ steps.dates.outputs.end }}" \
            --outdir "$CHUNK_DIR"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload chunk artifact
        uses: actions/upload-artifact@v4
        with:
          name: chunk-${{ matrix.chunk }}
          path: data/chunk-${{ matrix.chunk }}

  merge:
    needs: backfill
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download all chunk artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Combine all reports
        run: |
          mkdir -p data/japicmp data/output
          find artifacts/ -type f -path "*/japicmp/*.json" \
            -exec cp {} data/japicmp/ \;
          find artifacts/ -type f -path "*/output/*.json" \
            -exec cp {} data/output/ \;

      - name: Commit & push combined reports
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add data/japicmp data/output
            git commit -m "chore: backfill commit reports for last ${{ github.event.inputs.days }} days"
            git push
          else
            echo "No new reports to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Pages Deploy
        run: gh workflow run deploy-pages.yml --ref main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}